[project]
name = "polymarket-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dishka>=1.10.1",
    "nats-contracts",
    "nats-py>=2.15.0",
    "pydantic>=2.13.5",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[build-system]
requires = ["uv_build>=0.12.10,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "bot"
namespace = true

[tool.uv.sources]
nats-contracts = { git = "https://github.com/jakostawind-trading-bot-ops/nats_contracts.git", rev = "6e8b28be18fccba769bf18e22ce5613e01e903b9" }
