[project]
name = "polymarket-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.14.3",
    "dishka>=1.10.1",
    "httpx>=0.28.1",
    "nats-contracts",
    "nats-py>=2.15.0",
    "polymarket-sdk",
    "pydantic>=2.13.5",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[build-system]
requires = ["uv_build>=0.12.10,<0.13"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.uv.build-backend]
module-name = "bot"
namespace = true

[tool.uv.sources]
nats-contracts = { git = "https://github.com/jakostawind-trading-bot-ops/nats_contracts.git", rev = "5d77a1eed30ab0c13c152db1ff2c15745fb6568a" }
polymarket-sdk = { git = "https://github.com/jakostawind-trading-bot-ops/polymarket_sdk", rev = "396667daf22ecb90586a51937c4d933286cdbfbf" }
